// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gossip.proto
package server;
public final class GossipProto {
  private GossipProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface hearGossipRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 rpid = 1;
    /**
     * <code>optional int32 rpid = 1;</code>
     */
    boolean hasRpid();
    /**
     * <code>optional int32 rpid = 1;</code>
     */
    int getRpid();

    // optional int32 pid = 2;
    /**
     * <code>optional int32 pid = 2;</code>
     */
    boolean hasPid();
    /**
     * <code>optional int32 pid = 2;</code>
     */
    int getPid();

    // optional int32 noprocesses = 3;
    /**
     * <code>optional int32 noprocesses = 3;</code>
     */
    boolean hasNoprocesses();
    /**
     * <code>optional int32 noprocesses = 3;</code>
     */
    int getNoprocesses();

    // optional int32 clock = 4;
    /**
     * <code>optional int32 clock = 4;</code>
     */
    boolean hasClock();
    /**
     * <code>optional int32 clock = 4;</code>
     */
    int getClock();

    // optional string message = 5;
    /**
     * <code>optional string message = 5;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 5;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code hearGossipRequest}
   */
  public static final class hearGossipRequest extends
      com.google.protobuf.GeneratedMessage
      implements hearGossipRequestOrBuilder {
    // Use hearGossipRequest.newBuilder() to construct.
    private hearGossipRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private hearGossipRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final hearGossipRequest defaultInstance;
    public static hearGossipRequest getDefaultInstance() {
      return defaultInstance;
    }

    public hearGossipRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    @SuppressWarnings("unused")
	private hearGossipRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rpid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              noprocesses_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              clock_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GossipProto.internal_static_hearGossipRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GossipProto.internal_static_hearGossipRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GossipProto.hearGossipRequest.class, GossipProto.hearGossipRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<hearGossipRequest> PARSER =
        new com.google.protobuf.AbstractParser<hearGossipRequest>() {
      public hearGossipRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new hearGossipRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<hearGossipRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 rpid = 1;
    public static final int RPID_FIELD_NUMBER = 1;
    private int rpid_;
    /**
     * <code>optional int32 rpid = 1;</code>
     */
    public boolean hasRpid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 rpid = 1;</code>
     */
    public int getRpid() {
      return rpid_;
    }

    // optional int32 pid = 2;
    public static final int PID_FIELD_NUMBER = 2;
    private int pid_;
    /**
     * <code>optional int32 pid = 2;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 pid = 2;</code>
     */
    public int getPid() {
      return pid_;
    }

    // optional int32 noprocesses = 3;
    public static final int NOPROCESSES_FIELD_NUMBER = 3;
    private int noprocesses_;
    /**
     * <code>optional int32 noprocesses = 3;</code>
     */
    public boolean hasNoprocesses() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 noprocesses = 3;</code>
     */
    public int getNoprocesses() {
      return noprocesses_;
    }

    // optional int32 clock = 4;
    public static final int CLOCK_FIELD_NUMBER = 4;
    private int clock_;
    /**
     * <code>optional int32 clock = 4;</code>
     */
    public boolean hasClock() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 clock = 4;</code>
     */
    public int getClock() {
      return clock_;
    }

    // optional string message = 5;
    public static final int MESSAGE_FIELD_NUMBER = 5;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 5;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string message = 5;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rpid_ = 0;
      pid_ = 0;
      noprocesses_ = 0;
      clock_ = 0;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rpid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, noprocesses_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, clock_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rpid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, noprocesses_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, clock_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static GossipProto.hearGossipRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GossipProto.hearGossipRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GossipProto.hearGossipRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GossipProto.hearGossipRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GossipProto.hearGossipRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GossipProto.hearGossipRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GossipProto.hearGossipRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GossipProto.hearGossipRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GossipProto.hearGossipRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GossipProto.hearGossipRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GossipProto.hearGossipRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hearGossipRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements GossipProto.hearGossipRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GossipProto.internal_static_hearGossipRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GossipProto.internal_static_hearGossipRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GossipProto.hearGossipRequest.class, GossipProto.hearGossipRequest.Builder.class);
      }

      // Construct using GossipProto.hearGossipRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rpid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        noprocesses_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        clock_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GossipProto.internal_static_hearGossipRequest_descriptor;
      }

      public GossipProto.hearGossipRequest getDefaultInstanceForType() {
        return GossipProto.hearGossipRequest.getDefaultInstance();
      }

      public GossipProto.hearGossipRequest build() {
        GossipProto.hearGossipRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GossipProto.hearGossipRequest buildPartial() {
        GossipProto.hearGossipRequest result = new GossipProto.hearGossipRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rpid_ = rpid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.noprocesses_ = noprocesses_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clock_ = clock_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GossipProto.hearGossipRequest) {
          return mergeFrom((GossipProto.hearGossipRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GossipProto.hearGossipRequest other) {
        if (other == GossipProto.hearGossipRequest.getDefaultInstance()) return this;
        if (other.hasRpid()) {
          setRpid(other.getRpid());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasNoprocesses()) {
          setNoprocesses(other.getNoprocesses());
        }
        if (other.hasClock()) {
          setClock(other.getClock());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000010;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GossipProto.hearGossipRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GossipProto.hearGossipRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 rpid = 1;
      private int rpid_ ;
      /**
       * <code>optional int32 rpid = 1;</code>
       */
      public boolean hasRpid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 rpid = 1;</code>
       */
      public int getRpid() {
        return rpid_;
      }
      /**
       * <code>optional int32 rpid = 1;</code>
       */
      public Builder setRpid(int value) {
        bitField0_ |= 0x00000001;
        rpid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rpid = 1;</code>
       */
      public Builder clearRpid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rpid_ = 0;
        onChanged();
        return this;
      }

      // optional int32 pid = 2;
      private int pid_ ;
      /**
       * <code>optional int32 pid = 2;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 pid = 2;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>optional int32 pid = 2;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000002;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pid = 2;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        onChanged();
        return this;
      }

      // optional int32 noprocesses = 3;
      private int noprocesses_ ;
      /**
       * <code>optional int32 noprocesses = 3;</code>
       */
      public boolean hasNoprocesses() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 noprocesses = 3;</code>
       */
      public int getNoprocesses() {
        return noprocesses_;
      }
      /**
       * <code>optional int32 noprocesses = 3;</code>
       */
      public Builder setNoprocesses(int value) {
        bitField0_ |= 0x00000004;
        noprocesses_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 noprocesses = 3;</code>
       */
      public Builder clearNoprocesses() {
        bitField0_ = (bitField0_ & ~0x00000004);
        noprocesses_ = 0;
        onChanged();
        return this;
      }

      // optional int32 clock = 4;
      private int clock_ ;
      /**
       * <code>optional int32 clock = 4;</code>
       */
      public boolean hasClock() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 clock = 4;</code>
       */
      public int getClock() {
        return clock_;
      }
      /**
       * <code>optional int32 clock = 4;</code>
       */
      public Builder setClock(int value) {
        bitField0_ |= 0x00000008;
        clock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clock = 4;</code>
       */
      public Builder clearClock() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clock_ = 0;
        onChanged();
        return this;
      }

      // optional string message = 5;
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 5;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string message = 5;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 5;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 5;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 5;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hearGossipRequest)
    }

    static {
      defaultInstance = new hearGossipRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hearGossipRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearGossipRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearGossipRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Gossip.proto\"c\n\021hearGossipRequest\022\014\n\004r" +
      "pid\030\001 \001(\005\022\013\n\003pid\030\002 \001(\005\022\023\n\013noprocesses\030\003 " +
      "\001(\005\022\r\n\005clock\030\004 \001(\005\022\017\n\007message\030\005 \001(\tB\rB\013G" +
      "ossipProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hearGossipRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hearGossipRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearGossipRequest_descriptor,
              new java.lang.String[] { "Rpid", "Pid", "Noprocesses", "Clock", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
